neo:
  payment:
    tmnCode: BXNQA6LP
    secret-key: D9CFACCBB46B1E60B471FCBB35752F40
    ipn-url: http://localhost:9001/api/neo/call-back
    transaction-timeout: '900'
    max-retry-attempts: '3'
server:
  port: '8080'
spring:
  application:
    name: Neo Payment Sanbox
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    password: V0t1ng@2021
  #    url: jdbc:mysql://voting.local.active:3306/voting?useUnicode=yes&characterEncoding=UTF-8
  #    username: voting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          charSet: utf8mb4
          characterEncoding: utf8mb4
          useUnicode: 'true'
        format_sql: 'true'
    show-sql: 'true'
  thymeleaf:
    cache: 'false'
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      cache:
        period: '0'
      static-locations: file:src/main/resources/static/
